---
title: "Comedy and Mental Illness"
author: "John Ball"
date: "October 19, 2018"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Loaded in necessary libraries.
library(dplyr)
library(tidyverse)

# Read in df. Had to convert age from character to numeric.
updf <- read_csv("updf.csv") %>%
    mutate(Q4 = as.numeric(Q4))

# male and female datasets. 
female <- updf %>%
  filter(Q5 == 2)

male <- updf %>%
  filter(Q5 == 1)

# 4 datasets based on career income from comedy.
hobbyist <- updf %>%
  filter(Q7 == 1)

pursuit <- updf %>%
  filter(Q7 == 2)

professional <- updf %>%
  filter(Q7 == 3)

mixedinc <- updf %>%
  filter(Q7 == 4)

updf %>%
  filter(Q14_1 == 1) %>%
  filter(Q14_2 == 1) %>%
  filter(!is.na(Depression)) %>%
  summarize(mean(Depression))
#correlate with alcoholism scores



updf %>%
  filter(Q19 == 2) %>%
  filter(!is.na(Depression)) %>%
  summarize(mean(Depression), sd(Depression)) 


# From these statistics we can see that the comedy environment can enable alcoholism.
updf %>%
  filter(Q19 == 1) %>%
#  filter(!is.na(Problems)) %>%
  ggplot(aes(x = Problems)) + geom_histogram()
```


# Depression Histogram
```{r}
# Model histogram for depression, when in shiny app will replace "updf" with
# reactive dataframe.
ggplot(updf, aes(x = Depression)) + 
       geom_histogram(binwidth = 2, color = "black", fill = "light blue")

# Model descriptive statistics for Depression
updf %>%
  filter(!is.na(Depression)) %>%
  summarize(mean(Depression), sd(Depression))
```

# Hypomania Histogram
```{r}
# Model histogram for hypomania, when in shiny app will replace updf with
# reactive dataframe.
ggplot(updf, aes(x = Depression)) + 
       geom_histogram(binwidth = 2, color = "black", fill = "light blue")

updf %>%
  filter(!is.na(Hypomanic)) %>%
  summarize(mean(Hypomanic), sd(Hypomanic))
```



```{r}
#new %>%
#  summary()
#cmi %>%
#  summary()
#updf %>%
#  summary()
#still need to replace values which were unfilled

glimpse(updf)
zit <- updf

# Some people think depression is only prevalent among professionals, but it's clear this exists among amateurs as well. Does nto correlate with age.
ggplot(updf, aes(x = Q4, y = Depression)) + geom_point() +
  geom_smooth()

ggplot(updf, aes(x = Q4, y = Consumption)) + geom_point() +
  geom_smooth()

glimpse(updf)
```

```{r, warning = FALSE, message = FALSE}

# draft for depression

updf %>%
  ggplot(aes(x = Depression)) + 
  geom_histogram(binwidth = 2, color = "black", fill = "light blue") +
  labs(title = "Histogram of Depression Inventory Scores Among Comedians",
       x = "Depression Inventory Score",
       y = "Number of Comedians",
            subtitle = "Comedians Show Massively Increased Depression Scores Relative to General Population, With Control Median Being Less than 10")


# draft for big 5
b5 <- updf %>%
  select(Q5, Q7, Extraversion, Agreeableness, Conscientiousness, Neuroticism, Imagination) %>%
  drop_na()

summary(b5)


# draft for hypomania
h <- updf %>%
  select(Q4, Q5, Q7, Hypomanic) %>%
  filter(!is.na(Hypomanic))

h %>%
  mean(Hypomanic)

h %>%
  sd(Hypomanic)

# draft for alcoholism
alc <- updf %>%
  select(Q4, Q5, Q7, Consumption, Dependance, Problems, AUDITtot) %>%
  filter(!is.na(AUDITtot))

# draft for psychosis
olife <- updf %>%
  select(Q4, Q5, Q7, OLA, OCogDis, IntAnh, NonConf, OLifeT) %>%
  filter(!is.na(OLifeT))

updf %>%
  filter(Dependance >= 4) %>%
  count()

updf %>%
  filter(Dependance < 4) %>%
  count()

updf %>%
  filter(Problems > 0) %>%
  count()

updf %>%
  filter(Problems == 0) %>%
  count()

updf %>%
  count(Q7)

count(subset(datasetInput(), Dependance >= 4))
count(subset(datasetInput(), Dependance < 4))

count(subset(datasetInput(), Problems > 0))
count(subset(datasetInput(), Problems == 0))


  updf %>%
    count(Q15)
       
```

#####For context, the bell curve for average depression inventory scores in control populations can be found here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC34551/figure/F2/

```{r, warning = FALSE, message = FALSE}
#enjoyability of getting a laugh vs depression inventory scores among performers.
updf %>%
  filter(Q17 < 4) %>%
  ggplot(aes(x = Depression, y = Q16_1)) + 
  geom_point() +
  labs(title = "A Potential Mechanism for Increased Rates of Depression Among Comedians",
       x = "Depression Inventory Score", 
       y = "Enjoyability of Getting a Laugh Scored One Through Ten",
       subtitle = "One would expect enjoyability ratings of an experience to go down as anhedonic depressive symptoms increase. However, as depressive symptoms increase, comedians continue to rate getting a laugh as being 'euphoric'")
```



```{r}
#hypomanic
summary(h)

mean(h$Hypomanic)
sd(h$Hypomanic)

mean(datasetInput()$Hypomanic)
sd(datasetInput()$Hypomanic)

mean(alc$Consumption)
mean(datasetInput()$Consumption)


summary(alc)
```





```{r, eval = FALSE, warning = FALSE}
#student
cmi %>%
  filter(Q17 < 4) %>%
  filter(Q6 == 1) %>% 
  filter(!is.na(Depression)) %>%
  ggplot(aes(x = Depression)) + geom_histogram()



#depression mean score among people who had a "moment"
cmi %>%
  filter(Q17 < 4) %>%
  filter(Q20 == 1) %>% 
  filter(!is.na(Depression)) %>%
  summarize(mean_d = mean(Depression))


# effect of comedy on people who do have depression.
cmi %>%
  filter(Depression > 20) %>%
  group_by(Q15) %>%
  count()
  
# effect of comedy on people who do not have depression.
cmi %>%
  filter(Depression < 20) %>%
  group_by(Q15) %>%
  count()


# have you ever been diagnosed with depression?, 1 is yes 2 is no
cmi%>%
  filter(Q112 == 2) %>%
#  filter(Depression > 20) %>%
  ggplot(aes(x = Depression)) + geom_histogram()
  
updf %>%
  
  
# number of people diagnosed with depression. 
  cmi %>%
  filter(Q113_1 == 1) %>%
  count()

  ggplot(aes(x = Depression)) + geom_histogram()
```

